In [1]:
import pandas as pd 
import numpy as np

In [3]:
sales = pd.read_csv("fact_sales.csv")
sales.head(10)

,Invoice_ID,Order_Date,Customer_ID,Product_ID,Salesperson_ID,Quantity,Unit_Price,Discount_Percent,Sales_Amount,Cost_Amount,Profit,Payment_Mode,Delivery_Days,Return_Flag
0,INV000001,2025-12-12,CUST050,PROD067,SP12,129,182.45,0.00,23536.05,14227.41,9308.64,Credit Card,2,1
1,INV000002,2025-09-05,CUST035,PROD098,SP20,12,113.41,0.00,1360.92,1123.92,237.00,Credit Card,5,0
2,INV000003,2024-10-13,CUST047,PROD055,SP16,110,39.60,0.00,4356.00,2888.60,1467.40,Bank Transfer,4,0
3,INV000004,2025-10-09,CUST003,PROD016,SP13,27,47.33,0.00,1277.91,1004.67,273.24,Credit Card,5,0
4,INV000005,2024-09-04,CUST108,PROD065,SP20,36,98.37,0.00,3541.32,2146.68,1394.64,Cheque,6,0
5,INV000006,2025-05-23,CUST142,PROD036,SP01,118,217.36,0.00,25648.48,14944.70,10703.78,Credit Card,2,0
6,INV000007,2025-03-24,CUST075,PROD067,SP20,59,182.45,0.00,10764.55,6507.11,4257.44,Cheque,6,0
7,INV000008,2024-08-31,CUST012,PROD049,SP10,86,215.14,0.05,17576.94,12781.32,4795.62,Bank Transfer,2,0
8,INV000009,2024-05-13,CUST067,PROD080,SP07,18,54.57,0.00,982.26,698.76,283.50,Bank Transfer,2,0
9,INV000010,2025-04-10,CUST020,PROD082,SP10,29,60.60,0.00,1757.40,1172.47,584.93,Bank Transfer,1,0

In [4]:
sales.tail()

,Invoice_ID,Order_Date,Customer_ID,Product_ID,Salesperson_ID,Quantity,Unit_Price,Discount_Percent,Sales_Amount,Cost_Amount,Profit,Payment_Mode,Delivery_Days,Return_Flag
9995,INV009996,2024-05-17,CUST113,PROD049,SP14,50,215.14,0.00,10757.00,7431.00,3326.00,Credit Card,2,0
9996,INV009997,2024-08-19,CUST114,PROD073,SP01,74,220.00,0.05,15466.00,10885.40,4580.60,Credit Card,1,0
9997,INV009998,2025-01-10,CUST146,PROD007,SP03,75,210.04,0.00,15753.00,10106.25,5646.75,Credit Card,2,0
9998,INV009999,2025-01-27,CUST102,PROD096,SP08,25,62.46,0.00,1561.50,956.00,605.50,Bank Transfer,3,0
9999,INV010000,2024-02-28,CUST196,PROD023,SP09,104,67.67,0.00,7037.68,4409.60,2628.08,Cheque,3,0

In [5]:
sales.shape

(10000, 14)

In [6]:
sales.columns

Index(['Invoice_ID', 'Order_Date', 'Customer_ID', 'Product_ID',
       'Salesperson_ID', 'Quantity', 'Unit_Price', 'Discount_Percent',
       'Sales_Amount', 'Cost_Amount', 'Profit', 'Payment_Mode',
       'Delivery_Days', 'Return_Flag'],
      dtype='str')

In [8]:
sales.info

<bound method DataFrame.info of      Invoice_ID  Order_Date Customer_ID Product_ID Salesperson_ID  Quantity  \
0     INV000001  2025-12-12     CUST050    PROD067           SP12       129
1     INV000002  2025-09-05     CUST035    PROD098           SP20        12
2     INV000003  2024-10-13     CUST047    PROD055           SP16       110
3     INV000004  2025-10-09     CUST003    PROD016           SP13        27
4     INV000005  2024-09-04     CUST108    PROD065           SP20        36
...         ...         ...         ...        ...            ...       ...
9995  INV009996  2024-05-17     CUST113    PROD049           SP14        50
9996  INV009997  2024-08-19     CUST114    PROD073           SP01        74
9997  INV009998  2025-01-10     CUST146    PROD007           SP03        75
9998  INV009999  2025-01-27     CUST102    PROD096           SP08        25
9999  INV010000  2024-02-28     CUST196    PROD023           SP09       104

      Unit_Price  Discount_Percent  Sales_Amount  Cost_Amount   Profit  \
0         182.45              0.00      23536.05     14227.41  9308.64
1         113.41              0.00       1360.92      1123.92   237.00
2          39.60              0.00       4356.00      2888.60  1467.40
3          47.33              0.00       1277.91      1004.67   273.24
4          98.37              0.00       3541.32      2146.68  1394.64
...          ...               ...           ...          ...      ...
9995      215.14              0.00      10757.00      7431.00  3326.00
9996      220.00              0.05      15466.00     10885.40  4580.60
9997      210.04              0.00      15753.00     10106.25  5646.75
9998       62.46              0.00       1561.50       956.00   605.50
9999       67.67              0.00       7037.68      4409.60  2628.08

       Payment_Mode  Delivery_Days  Return_Flag
0       Credit Card              2            1
1       Credit Card              5            0
2     Bank Transfer              4            0
3       Credit Card              5            0
4            Cheque              6            0
...             ...            ...          ...
9995    Credit Card              2            0
9996    Credit Card              1            0
9997    Credit Card              2            0
9998  Bank Transfer              3            0
9999         Cheque              3            0

[10000 rows x 14 columns]>

In [14]:
sales['Discount_Percent'] = sales['Discount_Percent'] * 100

In [15]:
sales.tail

<bound method NDFrame.tail of      Invoice_ID  Order_Date Customer_ID Product_ID Salesperson_ID  Quantity  \
0     INV000001  2025-12-12     CUST050    PROD067           SP12       129
1     INV000002  2025-09-05     CUST035    PROD098           SP20        12
2     INV000003  2024-10-13     CUST047    PROD055           SP16       110
3     INV000004  2025-10-09     CUST003    PROD016           SP13        27
4     INV000005  2024-09-04     CUST108    PROD065           SP20        36
...         ...         ...         ...        ...            ...       ...
9995  INV009996  2024-05-17     CUST113    PROD049           SP14        50
9996  INV009997  2024-08-19     CUST114    PROD073           SP01        74
9997  INV009998  2025-01-10     CUST146    PROD007           SP03        75
9998  INV009999  2025-01-27     CUST102    PROD096           SP08        25
9999  INV010000  2024-02-28     CUST196    PROD023           SP09       104

      Unit_Price  Discount_Percent  Sales_Amount  Cost_Amount   Profit  \
0         182.45               0.0      23536.05     14227.41  9308.64
1         113.41               0.0       1360.92      1123.92   237.00
2          39.60               0.0       4356.00      2888.60  1467.40
3          47.33               0.0       1277.91      1004.67   273.24
4          98.37               0.0       3541.32      2146.68  1394.64
...          ...               ...           ...          ...      ...
9995      215.14               0.0      10757.00      7431.00  3326.00
9996      220.00               5.0      15466.00     10885.40  4580.60
9997      210.04               0.0      15753.00     10106.25  5646.75
9998       62.46               0.0       1561.50       956.00   605.50
9999       67.67               0.0       7037.68      4409.60  2628.08

       Payment_Mode  Delivery_Days  Return_Flag
0       Credit Card              2            1
1       Credit Card              5            0
2     Bank Transfer              4            0
3       Credit Card              5            0
4            Cheque              6            0
...             ...            ...          ...
9995    Credit Card              2            0
9996    Credit Card              1            0
9997    Credit Card              2            0
9998  Bank Transfer              3            0
9999         Cheque              3            0

[10000 rows x 14 columns]>

In [16]:
sales.isnull().sum

<bound method DataFrame.sum of       Invoice_ID  Order_Date  Customer_ID  Product_ID  Salesperson_ID  \
0          False       False        False       False           False
1          False       False        False       False           False
2          False       False        False       False           False
3          False       False        False       False           False
4          False       False        False       False           False
...          ...         ...          ...         ...             ...
9995       False       False        False       False           False
9996       False       False        False       False           False
9997       False       False        False       False           False
9998       False       False        False       False           False
9999       False       False        False       False           False

      Quantity  Unit_Price  Discount_Percent  Sales_Amount  Cost_Amount  \
0        False       False             False         False        False
1        False       False             False         False        False
2        False       False             False         False        False
3        False       False             False         False        False
4        False       False             False         False        False
...        ...         ...               ...           ...          ...
9995     False       False             False         False        False
9996     False       False             False         False        False
9997     False       False             False         False        False
9998     False       False             False         False        False
9999     False       False             False         False        False

      Profit  Payment_Mode  Delivery_Days  Return_Flag
0      False         False          False        False
1      False         False          False        False
2      False         False          False        False
3      False         False          False        False
4      False         False          False        False
...      ...           ...            ...          ...
9995   False         False          False        False
9996   False         False          False        False
9997   False         False          False        False
9998   False         False          False        False
9999   False         False          False        False

[10000 rows x 14 columns]>

In [17]:
sales.duplicated().sum()

np.int64(0)

In [24]:
sales['Order_Date'] = pd.to_datetime(sales['Order_Date'])

In [26]:
sales.head

<bound method NDFrame.head of      Invoice_ID Order_Date Customer_ID Product_ID Salesperson_ID  Quantity  \
0     INV000001 2025-12-12     CUST050    PROD067           SP12       129
1     INV000002 2025-09-05     CUST035    PROD098           SP20        12
2     INV000003 2024-10-13     CUST047    PROD055           SP16       110
3     INV000004 2025-10-09     CUST003    PROD016           SP13        27
4     INV000005 2024-09-04     CUST108    PROD065           SP20        36
...         ...        ...         ...        ...            ...       ...
9995  INV009996 2024-05-17     CUST113    PROD049           SP14        50
9996  INV009997 2024-08-19     CUST114    PROD073           SP01        74
9997  INV009998 2025-01-10     CUST146    PROD007           SP03        75
9998  INV009999 2025-01-27     CUST102    PROD096           SP08        25
9999  INV010000 2024-02-28     CUST196    PROD023           SP09       104

      Unit_Price  Discount_Percent  Sales_Amount  Cost_Amount   Profit  \
0         182.45               0.0      23536.05     14227.41  9308.64
1         113.41               0.0       1360.92      1123.92   237.00
2          39.60               0.0       4356.00      2888.60  1467.40
3          47.33               0.0       1277.91      1004.67   273.24
4          98.37               0.0       3541.32      2146.68  1394.64
...          ...               ...           ...          ...      ...
9995      215.14               0.0      10757.00      7431.00  3326.00
9996      220.00               5.0      15466.00     10885.40  4580.60
9997      210.04               0.0      15753.00     10106.25  5646.75
9998       62.46               0.0       1561.50       956.00   605.50
9999       67.67               0.0       7037.68      4409.60  2628.08

       Payment_Mode  Delivery_Days  Return_Flag
0       Credit Card              2            1
1       Credit Card              5            0
2     Bank Transfer              4            0
3       Credit Card              5            0
4            Cheque              6            0
...             ...            ...          ...
9995    Credit Card              2            0
9996    Credit Card              1            0
9997    Credit Card              2            0
9998  Bank Transfer              3            0
9999         Cheque              3            0

[10000 rows x 14 columns]>

In [28]:
sales.describe()

,Order_Date,Quantity,Unit_Price,Discount_Percent,Sales_Amount,Cost_Amount,Profit,Delivery_Days,Return_Flag
count,10000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,2024-12-29 16:09:07.200000,77.497900,114.426317,3.50500,8540.792104,5883.497489,2657.294615,3.509300,0.032000
min,2024-01-01 00:00:00,5.000000,7.430000,0.00000,52.010000,40.110000,11.900000,1.000000,0.000000
25%,2024-06-30 00:00:00,41.000000,57.470000,0.00000,2917.720000,2047.780000,722.505000,2.000000,0.000000
50%,2024-12-28 00:00:00,78.000000,107.110000,0.00000,6483.765000,4588.680000,1758.260000,4.000000,0.000000
75%,2025-07-01 00:00:00,114.000000,166.570000,5.00000,12303.522500,8505.562500,3688.175000,5.000000,0.000000
max,2025-12-30 00:00:00,149.000000,262.930000,15.00000,39176.570000,22144.380000,17382.340000,6.000000,1.000000
std,NaN,41.905973,65.737555,5.06434,7192.622549,4808.329957,2655.296218,1.714528,0.176009

In [34]:
sales[sales["Profit"] < 0]

Empty DataFrame
Columns: [Invoice_ID, Order_Date, Customer_ID, Product_ID, Salesperson_ID, Quantity, Unit_Price, Discount_Percent, Sales_Amount, Cost_Amount, Profit, Payment_Mode, Delivery_Days, Return_Flag]
Index: []

In [51]:
sales[(sales["Discount_Percent"] <=0)|(sales["Discount_Percent"] >= 100)]

,Invoice_ID,Order_Date,Customer_ID,Product_ID,Salesperson_ID,Quantity,Unit_Price,Discount_Percent,Sales_Amount,Cost_Amount,Profit,Payment_Mode,Delivery_Days,Return_Flag
0,INV000001,2025-12-12,CUST050,PROD067,SP12,129,182.45,0.0,23536.05,14227.41,9308.64,Credit Card,2,1
1,INV000002,2025-09-05,CUST035,PROD098,SP20,12,113.41,0.0,1360.92,1123.92,237.00,Credit Card,5,0
2,INV000003,2024-10-13,CUST047,PROD055,SP16,110,39.60,0.0,4356.00,2888.60,1467.40,Bank Transfer,4,0
3,INV000004,2025-10-09,CUST003,PROD016,SP13,27,47.33,0.0,1277.91,1004.67,273.24,Credit Card,5,0
4,INV000005,2024-09-04,CUST108,PROD065,SP20,36,98.37,0.0,3541.32,2146.68,1394.64,Cheque,6,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9991,INV009992,2024-10-05,CUST088,PROD015,SP20,93,28.02,0.0,2605.86,1949.28,656.58,Credit Card,2,0
9995,INV009996,2024-05-17,CUST113,PROD049,SP14,50,215.14,0.0,10757.00,7431.00,3326.00,Credit Card,2,0
9997,INV009998,2025-01-10,CUST146,PROD007,SP03,75,210.04,0.0,15753.00,10106.25,5646.75,Credit Card,2,0
9998,INV009999,2025-01-27,CUST102,PROD096,SP08,25,62.46,0.0,1561.50,956.00,605.50,Bank Transfer,3,0
9999,INV010000,2024-02-28,CUST196,PROD023,SP09,104,67.67,0.0,7037.68,4409.60,2628.08,Cheque,3,0

In [56]:
sales["Profit_Margin"] = (sales["Profit"]/sales["Sales_Amount"]) * 100

In [57]:
sales.head()

,Invoice_ID,Order_Date,Customer_ID,Product_ID,Salesperson_ID,Quantity,Unit_Price,Discount_Percent,Sales_Amount,Cost_Amount,Profit,Payment_Mode,Delivery_Days,Return_Flag,Profit_Margin
0,INV000001,2025-12-12,CUST050,PROD067,SP12,129,182.45,0.0,23536.05,14227.41,9308.64,Credit Card,2,1,39.550562
1,INV000002,2025-09-05,CUST035,PROD098,SP20,12,113.41,0.0,1360.92,1123.92,237.00,Credit Card,5,0,17.414690
2,INV000003,2024-10-13,CUST047,PROD055,SP16,110,39.60,0.0,4356.00,2888.60,1467.40,Bank Transfer,4,0,33.686869
3,INV000004,2025-10-09,CUST003,PROD016,SP13,27,47.33,0.0,1277.91,1004.67,273.24,Credit Card,5,0,21.381787
4,INV000005,2024-09-04,CUST108,PROD065,SP20,36,98.37,0.0,3541.32,2146.68,1394.64,Cheque,6,0,39.381925

In [59]:
sales["Year"] = sales["Order_Date"].dt.year

In [62]:
sales.head()

,Invoice_ID,Order_Date,Customer_ID,Product_ID,Salesperson_ID,Quantity,Unit_Price,Discount_Percent,Sales_Amount,Cost_Amount,Profit,Payment_Mode,Delivery_Days,Return_Flag,Profit_Margin,Year
0,INV000001,2025-12-12,CUST050,PROD067,SP12,129,182.45,0.0,23536.05,14227.41,9308.64,Credit Card,2,1,39.550562,2025
1,INV000002,2025-09-05,CUST035,PROD098,SP20,12,113.41,0.0,1360.92,1123.92,237.00,Credit Card,5,0,17.414690,2025
2,INV000003,2024-10-13,CUST047,PROD055,SP16,110,39.60,0.0,4356.00,2888.60,1467.40,Bank Transfer,4,0,33.686869,2024
3,INV000004,2025-10-09,CUST003,PROD016,SP13,27,47.33,0.0,1277.91,1004.67,273.24,Credit Card,5,0,21.381787,2025
4,INV000005,2024-09-04,CUST108,PROD065,SP20,36,98.37,0.0,3541.32,2146.68,1394.64,Cheque,6,0,39.381925,2024

In [63]:
sales["Month"] = sales["Order_Date"].dt.month_name()

In [64]:
sales.head()

,Invoice_ID,Order_Date,Customer_ID,Product_ID,Salesperson_ID,Quantity,Unit_Price,Discount_Percent,Sales_Amount,Cost_Amount,Profit,Payment_Mode,Delivery_Days,Return_Flag,Profit_Margin,Year,Month
0,INV000001,2025-12-12,CUST050,PROD067,SP12,129,182.45,0.0,23536.05,14227.41,9308.64,Credit Card,2,1,39.550562,2025,December
1,INV000002,2025-09-05,CUST035,PROD098,SP20,12,113.41,0.0,1360.92,1123.92,237.00,Credit Card,5,0,17.414690,2025,September
2,INV000003,2024-10-13,CUST047,PROD055,SP16,110,39.60,0.0,4356.00,2888.60,1467.40,Bank Transfer,4,0,33.686869,2024,October
3,INV000004,2025-10-09,CUST003,PROD016,SP13,27,47.33,0.0,1277.91,1004.67,273.24,Credit Card,5,0,21.381787,2025,October
4,INV000005,2024-09-04,CUST108,PROD065,SP20,36,98.37,0.0,3541.32,2146.68,1394.64,Cheque,6,0,39.381925,2024,September

In [66]:
sales["Quarter"] = sales["Order_Date"].dt.quarter

In [67]:
sales.head()

,Invoice_ID,Order_Date,Customer_ID,Product_ID,Salesperson_ID,Quantity,Unit_Price,Discount_Percent,Sales_Amount,Cost_Amount,Profit,Payment_Mode,Delivery_Days,Return_Flag,Profit_Margin,Year,Month,Quarter
0,INV000001,2025-12-12,CUST050,PROD067,SP12,129,182.45,0.0,23536.05,14227.41,9308.64,Credit Card,2,1,39.550562,2025,December,4
1,INV000002,2025-09-05,CUST035,PROD098,SP20,12,113.41,0.0,1360.92,1123.92,237.00,Credit Card,5,0,17.414690,2025,September,3
2,INV000003,2024-10-13,CUST047,PROD055,SP16,110,39.60,0.0,4356.00,2888.60,1467.40,Bank Transfer,4,0,33.686869,2024,October,4
3,INV000004,2025-10-09,CUST003,PROD016,SP13,27,47.33,0.0,1277.91,1004.67,273.24,Credit Card,5,0,21.381787,2025,October,4
4,INV000005,2024-09-04,CUST108,PROD065,SP20,36,98.37,0.0,3541.32,2146.68,1394.64,Cheque,6,0,39.381925,2024,September,3

In [69]:
sales["Payment_Mode"].unique()

<StringArray>
['Credit Card', 'Bank Transfer', 'Cheque', 'Cash']
Length: 4, dtype: str

In [71]:
sales["Return_Flag"].value_counts()

Return_Flag
0    9680
1     320
Name: count, dtype: int64

In [73]:
sales.to_csv("fact_sales_clean.csv",index=False)

In [74]:
inventory = pd.read_csv("fact_inventory.csv")

In [75]:
inventory.head()

,Product_ID,Warehouse,Opening_Stock,Stock_Received,Quantity_Sold,Current_Stock,Reorder_Level,Safety_Stock,Stock_Status,Expiry_Month
0,PROD001,WH-North,280,9813,9269,824,452,180,In Stock,2027-12
1,PROD002,WH-South,101,8833,8619,315,482,192,Reorder,2027-12
2,PROD003,WH-West,437,7455,7251,641,350,140,In Stock,2027-12
3,PROD004,WH-South,281,10217,9645,853,262,104,In Stock,2027-12
4,PROD005,WH-East,289,8276,7630,935,405,162,In Stock,2027-06

In [76]:
inventory.info

<bound method DataFrame.info of    Product_ID Warehouse  Opening_Stock  Stock_Received  Quantity_Sold  \
0     PROD001  WH-North            280            9813           9269
1     PROD002  WH-South            101            8833           8619
2     PROD003   WH-West            437            7455           7251
3     PROD004  WH-South            281           10217           9645
4     PROD005   WH-East            289            8276           7630
..        ...       ...            ...             ...            ...
95    PROD096   WH-East            949            8365           7650
96    PROD097   WH-West            985            8464           7509
97    PROD098  WH-South            136            9641           9332
98    PROD099  WH-South            858            7698           7261
99    PROD100  WH-South            364            7948           7465

    Current_Stock  Reorder_Level  Safety_Stock Stock_Status Expiry_Month
0             824            452           180     In Stock      2027-12
1             315            482           192      Reorder      2027-12
2             641            350           140     In Stock      2027-12
3             853            262           104     In Stock      2027-12
4             935            405           162     In Stock      2027-06
..            ...            ...           ...          ...          ...
95           1664            372           148     In Stock      2026-12
96           1940            440           176     In Stock      2027-06
97            445            209            83     In Stock      2027-03
98           1295            320           128     In Stock      2027-06
99            847            307           122     In Stock      2027-03

[100 rows x 10 columns]>

In [78]:
inventory.describe()

,Opening_Stock,Stock_Received,Quantity_Sold,Current_Stock,Reorder_Level,Safety_Stock
count,100.000000,100.00000,100.000000,100.000000,100.000000,100.000000
mean,507.360000,8277.08000,7749.790000,1034.650000,369.640000,147.440000
std,305.975556,958.65835,907.981815,530.053845,89.862917,35.941681
min,89.000000,6542.00000,5962.000000,134.000000,200.000000,80.000000
25%,278.750000,7673.25000,7101.750000,541.500000,292.250000,116.250000
50%,438.000000,8202.00000,7657.000000,980.500000,373.000000,149.000000
75%,704.250000,8845.75000,8255.250000,1418.250000,446.000000,177.750000
max,1321.000000,10790.00000,10065.000000,1983.000000,499.000000,199.000000

In [79]:
inventory[inventory["Current_Stock"] <= inventory["Reorder_Level"]]

,Product_ID,Warehouse,Opening_Stock,Stock_Received,Quantity_Sold,Current_Stock,Reorder_Level,Safety_Stock,Stock_Status,Expiry_Month
1,PROD002,WH-South,101,8833,8619,315,482,192,Reorder,2027-12
8,PROD009,WH-South,127,7836,7609,354,417,166,Reorder,2027-06
16,PROD017,WH-South,89,7979,7861,207,342,136,Reorder,2027-06
47,PROD048,WH-South,118,8218,8090,246,470,188,Reorder,2027-06
48,PROD049,WH-West,116,6685,6555,246,486,194,Reorder,2027-06
66,PROD067,WH-West,158,7581,7504,235,353,141,Reorder,2027-03
68,PROD069,WH-South,92,8065,8023,134,325,130,Reorder,2027-03
74,PROD075,WH-East,91,6622,6487,226,435,174,Reorder,2026-12
77,PROD078,WH-East,268,7443,7308,403,436,174,Reorder,2027-03
79,PROD080,WH-South,161,7327,7237,251,418,167,Reorder,2026-08

In [84]:
inventory["Stock_Status"].value_counts()

Stock_Status
In Stock    90
Reorder     10
Name: count, dtype: int64

In [91]:
inventory["Calculated_Stock"] = (
    inventory["Opening_Stock"] +
    inventory["Stock_Received"] -
    inventory["Quantity_Sold"]
)

In [92]:
inventory[["Current_Stock", "Calculated_Stock"]].head()

   Current_Stock  Calculated_Stock
0            824               824
1            315               315
2            641               641
3            853               853
4            935               935

In [94]:
inventory.to_csv("fact_inventory_clean.csv", index=False)

In [96]:
products = pd.read_csv("dim_products.csv")

In [97]:
products.shape

(100, 11)

In [98]:
products.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Product_ID         100 non-null    str
 1   Medicine_Name      100 non-null    str
 2   Generic_Name       100 non-null    str
 3   Category           100 non-null    str
 4   Manufacturer       100 non-null    str
 5   Dosage_Form        100 non-null    str
 6   Strength           100 non-null    str
 7   Pack_Size          100 non-null    str
 8   MRP                100 non-null    float64
 9   Cost_Price         100 non-null    float64
 10  Shelf_Life_Months  100 non-null    int64
dtypes: float64(2), int64(1), str(8)
memory usage: 5.5 KB

In [99]:
products["Medicine_Name"].duplicated().sum()

np.int64(3)

In [102]:
products["Category"].value_counts()

Category
Antidiabetics       15
Vitamins            14
Cardiovascular      13
Gastrointestinal    12
Antibiotics         11
Neurology            9
Analgesics           9
Dermatology          7
Respiratory          6
Anti-Allergy         4
Name: count, dtype: int64

In [104]:
products["Manufacturer"].value_counts()

Manufacturer
Johnson & Johnson       17
Pfizer                  16
Roche                   14
GSK                     13
AstraZeneca             11
Sanofi                   8
AbbVie                   6
Merck                    6
Bristol Myers Squibb     5
Novartis                 4
Name: count, dtype: int64

In [105]:
products["Shelf_Life_Months"].describe()

count    100.00000
mean      22.56000
std        8.86751
min       12.00000
25%       18.00000
50%       18.00000
75%       36.00000
max       36.00000
Name: Shelf_Life_Months, dtype: float64

In [107]:
products.to_csv("dim_products_clean.csv", index=False)

In [108]:
salesperson = pd.read_csv("dim_salesperson.csv")

In [109]:
salesperson.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Salesperson_ID    20 non-null     str
 1   Salesperson_Name  20 non-null     str
 2   Territory         20 non-null     str
 3   Experience_Years  20 non-null     int64
 4   Target            20 non-null     int64
 5   Manager           20 non-null     str
dtypes: int64(2), str(4)
memory usage: 712.0 bytes

In [110]:
salesperson.shape

(20, 6)

In [117]:
salesperson["Territory"].value_counts()

Territory
Northeast    7
West         6
South        4
Midwest      3
Name: count, dtype: int64

In [118]:
salesperson["Target"].describe()

count        20.000000
mean     180000.000000
std       61558.701125
min      100000.000000
25%      137500.000000
50%      175000.000000
75%      250000.000000
max      250000.000000
Name: Target, dtype: float64

In [119]:
salesperson["Manager"].value_counts()

Manager
Bob Manager        5
Charlie Manager    5
Diana Manager      5
Alice Manager      5
Name: count, dtype: int64

In [121]:
salesperson.to_csv("dim_salesperson_clean.csv", index=False)

In [123]:
dates = pd.read_csv("dim_dates.csv")

In [124]:
dates.info()

<class 'pandas.DataFrame'>
RangeIndex: 730 entries, 0 to 729
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Date        730 non-null    str
 1   Day         730 non-null    int64
 2   Month       730 non-null    int64
 3   Month_Name  730 non-null    str
 4   Quarter     730 non-null    int64
 5   Year        730 non-null    int64
 6   Weekday     730 non-null    str
 7   Weekend     730 non-null    int64
dtypes: int64(5), str(3)
memory usage: 37.1 KB

In [126]:
dates.shape

(730, 8)

In [127]:
dates["Year"].value_counts()

Year
2024    366
2025    364
Name: count, dtype: int64

In [128]:
dates.to_csv("dim_dates_clean.csv", index=False)